import devEnv from './env.development'
import prodEnv from './env.production'
import type { Coins } from './types/domain'

// Import local config if it exists (generated by deploy_local_helper.sh)
// Use import.meta.glob to conditionally import env.local.ts
const localModules = import.meta.glob('./env.local.ts', { eager: true, import: 'default' }) as Record<string, typeof devEnv>
const localEnv = localModules['./env.local.ts']

// Only use local config when VITE_BRIDGE_LOCAL_DEBUG=true
// Otherwise use devEnv (development) or prodEnv (production)
const useLocalDebug = import.meta.env.VITE_BRIDGE_LOCAL_DEBUG === 'true'

const env = ((useLocalDebug && localEnv) ? localEnv : (import.meta.env.MODE === 'development' ? devEnv : prodEnv)) as {
  apis: {
    '/transfers': string
    '/estimate_fees': string
    committees: {
      signs: string[]
    }
  }
  coins: Coins
  bridge: {
    evm: {
      chainIdHex: string
      chainId: number
      bridgeAddress: string
      destinationChainId: number
    }
    starcoin: {
      packageAddress: string
      chainId: number
    }
    tokens: {
      USDT?: { tokenId: number; claimFunction: 'claim_bridge_usdt' }
      AnvilUSDT?: { tokenId: number; claimFunction: 'claim_bridge_usdt' }
      SepoliaUSDT?: { tokenId: number; claimFunction: 'claim_bridge_usdt' }
      StarUSDT: { tokenId: number; claimFunction: 'claim_bridge_usdt'; sendFunction: 'send_bridge_usdt'; decimals: number }
    }
  }
  icons: Record<string, string>
}

export default env
